name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode-13.4.1.app/Contents/Developer
    
    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      run: xcodebuild clean build test -workspace ARFoodie/ARFoodieApp.xcworkspace -scheme ARFoodie CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRE=NO
